In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[2983, 7422, 5268, 6064],
 [2983, 7422, 5268, 7912],
 [2983, 1777, 5268, 3002],
 [557, 9468, 6224, 9091, 6074],
 [557, 9468, 6224, 9091, 8554],
 [9858, 2983, 3109, 5268, 7195],
 [46, 7762, 1480, 9091]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2983 7422 5268 6064]
 [   0    0    0    0 2983 7422 5268 7912]
 [   0    0    0    0 2983 1777 5268 3002]
 [   0    0    0  557 9468 6224 9091 6074]
 [   0    0    0  557 9468 6224 9091 8554]
 [   0    0    0 9858 2983 3109 5268 7195]
 [   0    0    0    0   46 7762 1480 9091]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\adiad\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [16]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (7, 8, 10)             │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [17]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step


array([[[ 0.0191392 , -0.03408567, -0.00780971,  0.01113143,
         -0.01963116,  0.00772742,  0.04790784, -0.03152319,
         -0.04110485, -0.00644457],
        [ 0.0191392 , -0.03408567, -0.00780971,  0.01113143,
         -0.01963116,  0.00772742,  0.04790784, -0.03152319,
         -0.04110485, -0.00644457],
        [ 0.0191392 , -0.03408567, -0.00780971,  0.01113143,
         -0.01963116,  0.00772742,  0.04790784, -0.03152319,
         -0.04110485, -0.00644457],
        [ 0.0191392 , -0.03408567, -0.00780971,  0.01113143,
         -0.01963116,  0.00772742,  0.04790784, -0.03152319,
         -0.04110485, -0.00644457],
        [-0.02415892, -0.03709912, -0.04020003,  0.04069171,
          0.04766632,  0.04851618, -0.03775774,  0.00307194,
         -0.03863025,  0.03273121],
        [ 0.04174873,  0.00184274, -0.03840367,  0.00716492,
         -0.00596203, -0.02142069,  0.02184728,  0.0392178 ,
          0.02396644,  0.01750674],
        [-0.04851874,  0.04572221,  0.0059389 , -0.0

In [18]:
embedded_docs[0]

array([   0,    0,    0,    0, 2983, 7422, 5268, 6064])